### ISSUE TITLE
timetable_helper.get_timetable() throws error

### ISSUE THREAD

**Issue by paurf** [Tutorialwork/deutsche_bahn_api#7]
I try to use your code as shown in the demonstration. Is it still maintained? 

When I run
```
from deutsche_bahn_api.api_authentication import ApiAuthentication
from deutsche_bahn_api.station_helper import StationHelper
from deutsche_bahn_api.timetable_helper import TimetableHelper

CLIENT_ID = 
CLIENT_API = 

api = ApiAuthentication(CLIENT_ID, CLIENT_API)
print(api.test_credentials())

station_helper = StationHelper()
found_stations = station_helper.find_stations_by_name("Ulm Hbf")

station = found_stations[0]

print(found_stations)
print(type(found_stations))

timetable_helper = TimetableHelper(station, CLIENT_API)
trains_in_this_hour = timetable_helper.get_timetable()

print(type(trains_in_this_hour))
print(trains_in_this_hour)

````
I get

```
True
[Station(EVA_NR=8000170, DS100='TU', IFOPT='de:08421:1008', NAME='Ulm Hbf', Verkehr='FV', Laenge='9,982227', Breite='48,399437', Betreiber_Name='DB Station und Service AG', Betreiber_Nr=6323, Status='')]
<class 'list'>
Traceback (most recent call last):
  File "/home/pi/python/bahn_api/main.py", line 20, in <module>
    trains_in_this_hour = timetable_helper.get_timetable()
  File "/home/pi/.local/lib/python3.9/site-packages/deutsche_bahn_api/timetable_helper.py", line 49, in get_timetable
    trains = elementTree.fromstringlist(self.get_timetable_xml(hour))
  File "/home/pi/.local/lib/python3.9/site-packages/deutsche_bahn_api/timetable_helper.py", line 35, in get_timetable_xml
    headers=self.api_authentication.get_headers()
AttributeError: 'str' object has no attribute 'get_headers'

```
It seems something might have changed in the API?

**Comment by phiyodr** [comment]
Hi,
please use 
```python
timetable_helper = TimetableHelper(station, api)
```

instead of 

```python
timetable_helper = TimetableHelper(station, CLIENT_API)
```

**Comment by JoergZ2** [comment]
This code works fine:
```
from deutsche_bahn_api.api_authentication import ApiAuthentication
from deutsche_bahn_api.station_helper import StationHelper
from deutsche_bahn_api.timetable_helper import TimetableHelper
client_id = "myClientId"
API_Key = "myApiKey"

api = ApiAuthentication(client_id, API_Key)
station_helper = StationHelper()
found_stations_by_name = station_helper.find_stations_by_name("Salzwedel")
station = found_stations_by_name[0]
timetable_helper = TimetableHelper(station, api)
connections = timetable_helper.get_timetable()

trains_with_changes = timetable_helper.get_timetable_changes(connections)

for train in trains_with_changes:
    print("Train Number:", train.train_number)
    print("Train Type:", train.train_type)
    print("Platform:", train.platform)
    print("Departure:", train.departure)
    print("\n")
```
But when I replace line 14 with:
```
trains_with_changes = timetable_helper.get_timetable(connections)
```
it throws  this errors:
```
Traceback (most recent call last):
  File "/home/jz/Skripte/python/API/bahn_05.py", line 15, in <module>
    trains_with_changes = timetable_helper.get_timetable(connections)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jz/.venvs/db/lib/python3.11/site-packages/deutsche_bahn_api/timetable_helper.py", line 49, in get_timetable
    trains = elementTree.fromstringlist(self.get_timetable_xml(hour=hour, date=date))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jz/.venvs/db/lib/python3.11/site-packages/deutsche_bahn_api/timetable_helper.py", line 27, in get_timetable_xml
    hour_date = datetime.strptime(str(hour), "%H")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '[<deutsche_bahn_api.train.Train object at 0x71c65cf1f290>, <deutsche_bahn_api.train.Train object at 0x71c65d17dfd0>, <deutsche_bahn_api.train.Train object at 0x71c65cf427d0>, <deutsche_bahn_api.train.Train object at 0x71c65cf42950>, <deutsche_bahn_api.train.Train object at 0x71c65cf42b10>, <deutsche_bahn_api.train.Train object at 0x71c65cf42e50>, <deutsche_bahn_api.train.Train object at 0x71c65cf43010>, <deutsche_bahn_api.train.Train object at 0x71c65cf431d0>, <deutsche_bahn_api.train.Train object at 0x71c65cf43390>, <deutsche_bahn_api.train.Train object at 0x71c65cf42cd0>, <deutsche_bahn_api.train.Train object at 0x71c65cf43510>, <deutsche_bahn_api.train.Train object at 0x71c65cf436d0>, <deutsche_bahn_api.train.Train object at 0x71c65cf43890>, <deutsche_bahn_api.train.Train object at 0x71c65cf43a50>, <deutsche_bahn_api.train.Train object at 0x71c65cf43bd0>, <deutsche_bahn_api.train.Train object at 0x71c65cf43d90>, <deutsche_bahn_api.train.Train object at 0x71c65cf43f10>, <deutsche_bahn_api.train.Train object at 0x71c65cf48110>, <deutsche_bahn_api.train.Train object at 0x71c65cf48250>, <deutsche_bahn_api.train.Train object at 0x71c65cf483d0>, <deutsche_bahn_api.train.Train object at 0x71c65cf48590>, <deutsche_bahn_api.train.Train object at 0x71c65cf48750>, <deutsche_bahn_api.train.Train object at 0x71c65cf48910>, <deutsche_bahn_api.train.Train object at 0x71c65cf48a90>, <deutsche_bahn_api.train.Train object at 0x71c65cf48c10>]' 
does not match format '%H'
```
What is the correct expression to call the timetable of current hour?
